name: Build LaTeX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repo
      uses: actions/checkout@v1
    - name: Download fonts
      run: |
        curl -LO http://penoy.admu.edu.ph/~guadalupe154884/files/_fonts.zip
        unzip _fonts.zip
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        extra_system_packages: "alpine-sdk py-pygments"
        compiler: make
    - name: Check pdf files
      run: |
        set -e
        file main.pdf | grep -q ' PDF '
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: main.pdf
        path: main.pdf
      if: always()
